# Generated by Django 3.1 on 2020-08-06 02:32

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200731_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to='images'),
        ),
    ]
