# Generated by Django 3.0.8 on 2020-07-20 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestOfferPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='post_images')),
                ('title', models.CharField(blank=True, max_length=80, null=True)),
                ('post_text', models.TextField(blank=True, help_text='What do you need? What can you give?', max_length=500, null=True)),
                ('fulfilled', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('kids', 'kids'), ('yard/garden', 'yard/garden'), ('odd job', 'odd job'), ('skilled labor', 'skilled labor'), ('food', 'food'), ('clothing', 'clothing'), ('homegoods', 'homegoods'), ('furniture', 'furniture'), ('books', 'books')], max_length=25)),
                ('request_or_offer', models.CharField(choices=[('Request', 'Request'), ('Offer', 'Offer')], max_length=50)),
                ('timeline_start', models.DateField()),
                ('timeline_end', models.DateField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='posts', to='obodo.Tag')),
            ],
        ),
    ]
