# Generated by Django 3.0.8 on 2020-07-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestofferpost',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='obodo.Photo'),
        ),
    ]
