# Generated by Django 3.0.8 on 2020-07-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0006_auto_20200720_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestofferpost',
            old_name='image',
            new_name='post_image',
        ),
    ]
