# Generated by Django 3.0.8 on 2020-07-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obodo', '0008_photo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, null=True)),
                ('community', models.CharField(choices=[('Raleigh', 'Raleigh'), ('Durham', 'Durham'), ('Wake Forest', 'Wake Forest'), ('Chapel Hill', 'Chapel Hill'), ('Cary', 'Cary'), ('Apex/Holly Springs', 'Apex/Holly Springs'), ('Garner', 'Garner'), ('Clayton', 'Clayton'), ('Knightdale/Zebulon', 'Knightdale/Zebulon')], default='', max_length=55)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
                ('profile_pic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='obodo.Photo')),
            ],
        ),
    ]
