# Generated by Django 3.0.8 on 2020-07-21 16:36

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestofferpost',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default='', map_attrs={}, null=True),
        ),
    ]
