# Generated by Django 3.0.8 on 2020-07-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0011_auto_20200721_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='obodo.RequestOfferPost'),
        ),
        migrations.AlterField(
            model_name='requestofferpost',
            name='post_image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
