# Generated by Django 3.0.8 on 2020-07-21 17:22

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0012_auto_20200721_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestofferpost',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default='', map_attrs={'center': [0, 0], 'marker_color': 'blue'}, null=True),
        ),
    ]
