# Generated by Django 3.0.8 on 2020-07-21 23:08

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0013_auto_20200721_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestofferpost',
            name='location',
            field=mapbox_location_field.models.LocationField(blank=True, default='', map_attrs={'center': [0, 0], 'geocoder': True, 'marker_color': 'blue', 'track_location_button': True}, null=True),
        ),
    ]
