# Generated by Django 3.0.8 on 2020-07-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0014_auto_20200721_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='post',
        ),
    ]
