# Generated by Django 3.0.8 on 2020-07-25 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obodo', '0016_auto_20200723_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.CharField(choices=[('Raleigh', 'Raleigh'), ('Durham', 'Durham'), ('Wake Forest', 'Wake Forest'), ('Chapel Hill', 'Chapel Hill'), ('Cary', 'Cary'), ('Apex/Holly Springs', 'Apex/Holly Springs'), ('Garner', 'Garner'), ('Clayton', 'Clayton'), ('Knightdale/Zebulon', 'Knightdale/Zebulon')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('original_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='obodo.RequestOfferPost')),
            ],
        ),
    ]
