# Generated by Django 3.0.8 on 2020-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0016_auto_20200723_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestofferpost',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
