# Generated by Django 3.0.8 on 2020-07-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0016_auto_20200723_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestofferpost',
            name='category',
            field=models.CharField(choices=[('kids', 'kids'), ('outdoors', 'outdoors'), ('services', 'services'), ('food', 'food'), ('clothing', 'clothing'), ('homegoods', 'homegoods'), ('furniture', 'furniture'), ('books', 'books')], max_length=25),
        ),
    ]
