# Generated by Django 3.0.8 on 2020-07-25 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0018_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
