# Generated by Django 3.0.8 on 2020-07-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0019_auto_20200725_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
