# Generated by Django 3.0.8 on 2020-07-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0020_event_event_title'),
        ('obodo', '0017_comment_community'),
    ]

    operations = [
    ]
