# Generated by Django 3.0.8 on 2020-07-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0017_auto_20200725_2021'),
        ('obodo', '0017_comment_community'),
        ('obodo', '0020_event_event_title'),
    ]

    operations = [
    ]
