# Generated by Django 3.0.8 on 2020-07-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0021_merge_20200726_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='community',
        ),
    ]
