# Generated by Django 3.0.8 on 2020-07-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0021_merge_20200726_1944'),
        ('obodo', '0022_auto_20200726_1856'),
    ]

    operations = [
    ]
