# Generated by Django 3.0.8 on 2020-07-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0023_requestofferpost_community'),
        ('obodo', '0021_merge_20200726_1944'),
    ]

    operations = [
    ]
