# Generated by Django 3.0.8 on 2020-07-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0023_merge_20200726_2230'),
        ('obodo', '0023_requestofferpost_community'),
    ]

    operations = [
    ]
