# Generated by Django 3.0.8 on 2020-07-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0024_merge_20200727_2321'),
        ('obodo', '0024_merge_20200728_1458'),
    ]

    operations = [
    ]
