# Generated by Django 3.0.8 on 2020-07-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0025_auto_20200728_1848'),
        ('obodo', '0025_merge_20200728_1601'),
    ]

    operations = [
    ]
