# Generated by Django 3.0.8 on 2020-07-29 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0024_merge_20200728_0203'),
        ('obodo', '0025_merge_20200728_1601'),
    ]

    operations = [
    ]
