# Generated by Django 3.0.8 on 2020-07-29 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0027_profile'),
        ('obodo', '0026_merge_20200729_0024'),
    ]

    operations = [
    ]
