# Generated by Django 3.0.8 on 2020-07-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0028_merge_20200729_2012'),
        ('obodo', '0028_merge_20200729_1915'),
    ]

    operations = [
    ]
