# Generated by Django 3.0.8 on 2020-07-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0029_merge_20200731_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestofferpost',
            name='timeline_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requestofferpost',
            name='timeline_start',
            field=models.DateTimeField(),
        ),
    ]
