# Generated by Django 3.0.8 on 2020-07-31 21:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0031_auto_20200731_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestofferpost',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images'),
        ),
    ]
