# Generated by Django 3.0.8 on 2020-08-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0029_merge_20200801_1700'),
        ('obodo', '0033_auto_20200731_2137'),
    ]

    operations = [
    ]
