# Generated by Django 3.0.8 on 2020-08-01 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0033_auto_20200731_2137'),
        ('obodo', '0029_merge_20200730_1917'),
    ]

    operations = [
    ]
