# Generated by Django 3.0.8 on 2020-08-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0029_merge_20200801_1700'),
        ('obodo', '0034_merge_20200801_1847'),
    ]

    operations = [
    ]
