# Generated by Django 3.1 on 2020-08-06 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0034_merge_20200801_2000'),
        ('obodo', '0035_merge_20200802_1724'),
    ]

    operations = [
    ]
