# Generated by Django 3.0.8 on 2020-08-05 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0035_merge_20200802_1724'),
        ('obodo', '0034_merge_20200801_2000'),
    ]

    operations = [
    ]
