# Generated by Django 3.1 on 2020-08-06 02:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('obodo', '0036_merge_20200806_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='requestofferpost',
            name='post_image',
            field=imagekit.models.fields.ProcessedImageField(default='default.jpeg', upload_to='images'),
        ),
    ]
